Traceback (most recent call last):
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/gslee/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
price = pd.read_pickle('examples/yahoo_price.pkl')
price
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/tmp/ipykernel_736/4260892097.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mprice[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mread_pickle[0m[0;34m([0m[0;34m'examples/yahoo_price.pkl'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mprice[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.9/site-packages/pandas/io/pickle.py[0m in [0;36mread_pickle[0;34m(filepath_or_buffer, compression, storage_options)[0m
[1;32m    194[0m     """
[1;32m    195[0m     [0mexcs_to_catch[0m [0;34m=[0m [0;34m([0m[0mAttributeError[0m[0;34m,[0m [0mImportError[0m[0;34m,[0m [0mModuleNotFoundError[0m[0;34m,[0m [0mTypeError[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 196[0;31m     with get_handle(
[0m[1;32m    197[0m         [0mfilepath_or_buffer[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    198[0m         [0;34m"rb"[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.9/site-packages/pandas/io/common.py[0m in [0;36mget_handle[0;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[1;32m    709[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    710[0m             [0;31m# Binary mode[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 711[0;31m             [0mhandle[0m [0;34m=[0m [0mopen[0m[0;34m([0m[0mhandle[0m[0;34m,[0m [0mioargs[0m[0;34m.[0m[0mmode[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    712[0m         [0mhandles[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0mhandle[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    713[0m [0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'examples/yahoo_price.pkl'
FileNotFoundError: [Errno 2] No such file or directory: 'examples/yahoo_price.pkl'

