Traceback (most recent call last):
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/gslee/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/gslee/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
if pd.Series([False, True, False]):
     print("I was true")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Input [0;32mIn [186][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [38;5;28;01mif[39;00m pd[38;5;241m.[39mSeries([[38;5;28;01mFalse[39;00m, [38;5;28;01mTrue[39;00m, [38;5;28;01mFalse[39;00m]):
[1;32m      2[0m      [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mI was true[39m[38;5;124m"[39m)

File [0;32m~/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py:1527[0m, in [0;36mNDFrame.__nonzero__[0;34m(self)[0m
[1;32m   1525[0m [38;5;129m@final[39m
[1;32m   1526[0m [38;5;28;01mdef[39;00m [38;5;21m__nonzero__[39m([38;5;28mself[39m):
[0;32m-> 1527[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m   1528[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mThe truth value of a [39m[38;5;132;01m{[39;00m[38;5;28mtype[39m([38;5;28mself[39m)[38;5;241m.[39m[38;5;18m__name__[39m[38;5;132;01m}[39;00m[38;5;124m is ambiguous. [39m[38;5;124m"[39m
[1;32m   1529[0m         [38;5;124m"[39m[38;5;124mUse a.empty, a.bool(), a.item(), a.any() or a.all().[39m[38;5;124m"[39m
[1;32m   1530[0m     )

[0;31mValueError[0m: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

